// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkxxdwaidxisdjqgeeej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZreHhkd2FpZHhpc2RqcWdlZWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjE2NzIsImV4cCI6MjA3MTE5NzY3Mn0.Hv7vJHIJYvrLWsjpIh1rvcgg_q5qSKvtVxLG26Ogs_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});